# Generated by Django 4.2.5 on 2025-02-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='buyer',
            new_name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_holder',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_number',
            field=models.CharField(default=0, max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='expiry_date',
            field=models.CharField(default='12/25', max_length=5),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pin',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SELL', 'Sell to Platform'), ('BUY', 'Buy from Platform')], max_length=4),
        ),
    ]
