# Generated by Django 4.2.5 on 2025-02-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_buyer_transaction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='giftcards/backgrounds/'),
        ),
    ]
