# Generated by Django 4.2.5 on 2025-02-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_giftcard_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
