# Generated by Django 4.2.5 on 2025-02-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_giftcard_background_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftcard',
            old_name='amount',
            new_name='buy_back_price',
        ),
        migrations.AddField(
            model_name='giftcard',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
