# Generated by Django 4.2.5 on 2025-02-23 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_giftcard_buy_back_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('UPI', 'UPI'), ('DEBIT_CARD', 'Debit Card'), ('CREDIT_CARD', 'Credit Card'), ('NETBANKING', 'Net Banking'), ('WALLETS_GOOGLE', 'Wallet - Google Pay'), ('WALLETS_AMAZON', 'Wallet - Amazon Pay'), ('WALLETS_OLA', 'Wallet - Ola Money'), ('GIFT_VOUCHER', 'Gift Voucher')], max_length=50, verbose_name='Payment Method')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress')], default='PENDING', max_length=50, verbose_name='Payment Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
