# Generated by Django 4.2.5 on 2025-04-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_salepayment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="method",
            field=models.CharField(
                choices=[
                    ("DEBIT_CARD", "Debit Card"),
                    ("CREDIT_CARD", "Credit Card"),
                    ("NETBANKING", "Net Banking"),
                ],
                max_length=50,
                verbose_name="Payment Mode",
            ),
        ),
    ]
