# Generated by Django 4.2.5 on 2025-04-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_giftcard_is_active_salepayment_gift_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="card_number",
            field=models.CharField(max_length=16),
        ),
    ]
